debugLevel: DEBUG
api:
  cv:
    port: 8091
    url: http://localhost:8091
    expectedHosts:
      - localhost:8091
      - localhost:8092
  monitoring:
    port: 8092
    expectedHosts:
      - localhost:8091
db:
  cassandra:
    url: "127.0.0.1"
    keyspace: "cv"
    retries: 3
    username: cassandra
    secret: cassandra
