# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  cassandra:
    image: cassandra:4.1.3
    container_name: cassandra_cv
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
      - "CASSANDRA_PASSWORD_SEEDER=yes"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.1.3
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./sql/schema/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: cassandra-web_cv
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "3001:3000"
      - "8183:8083"
    environment:
      CASSANDRA_HOST_IP: 10.6.0.11
      CASSANDRA_PORT: 9042
      USERNAME: cassandra
      PASSWORD: cassandra

  kafka:
    image: docker.io/bitnami/kafka:3.8.1
    container_name: kafka_cv
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui_cv
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"

volumes:
  kafka_data:
    driver: local
