services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
      - "7001:7001"
      - "7199:7199"
      - "9160:9160"
    environment:
      CASSANDRA_SEEDS: 10.6.0.11
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_PASSWORD_SEEDER: "yes"
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    networks:
      default:
        ipv4_address: 10.6.0.11
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.1.3
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./sql/schema/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
  cassandra-web:
    image: ipushc/cassandra-web:latest
    container_name: cassandra-web
    depends_on:
      - cassandra
    ports:
      - "3000:3000"
      - "8183:8083"
    environment:
      CASSANDRA_HOST_IP: 10.6.0.11
      CASSANDRA_PORT: 9042
      USERNAME: cassandra
      PASSWORD: cassandra

  opensearch-node1:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Pass*w0rd!
      - "plugins.security.disabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/24
