debugLevel: DEBUG
api:
  url: http://localhost
  cv:
    port: 8091
    expectedHosts:
      - localhost:8091
  monitoring:
    port: 8092
db:
  cassandra:
    url: "127.0.0.1"
    port: 9042
    keyspace: "cv"
    retries: 3
    username: cassandra
    secret: cassandra
  neo4j:
    url: neo4j://localhost
    port: "7687"
    username: neo4j
    secret: Pass*w0rd!
