@startuml "overview"

package cmd.api {
    class main
}

package api {
    class api implements cv_server_gen

    cmd.api.main -> api
}

package domain {
    class experience
    class experience_service

    api.api -> experience_service
}

package clients.cassandra {
    class cassandra

    domain.experience_service -down-> cassandra
}


@enduml