@startuml "overview"

package cmd {
    class main
}

package api {
    class cv_api_impl implements cv_server_gen

    cmd.main -> cv_api_impl
}

package domain {

    package model {
        class experience
    }

    package services {
        class experience_service
    }

    api.cv_api_impl -> services.experience_service
}

package clients.db {

    class ExperienceDbAdapter

    package cassandra {
        class cassandra
    }

    domain.services.experience_service -down-> ExperienceDbAdapter
}


@enduml
