@startuml "overview"

package cmd.api {

    class main

}

package pkg.api {
    class api implements cv_server_gen

    cmd.api.main -> api
}

package pkg.domain {
    class experience
    class experience_service

    pkg.api.api -> experience_service
}

package pkg.clients.cassandra {
    class cassandra

    pkg.domain.experience_service -down-> cassandra
}


@enduml