// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateExperienceRequest defines model for CreateExperienceRequest.
type CreateExperienceRequest struct {
	Name string `json:"name"`
	Tags *[]Tag `json:"tags,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code      string             `json:"code"`
	Message   string             `json:"message"`
	RequestId openapi_types.UUID `json:"requestId"`
}

// Experience defines model for Experience.
type Experience struct {
	Id   *int64 `json:"id,omitempty"`
	Name string `json:"name"`
}

// ExperiencePayload defines model for ExperiencePayload.
type ExperiencePayload struct {
	Name string `json:"name"`
}

// Experiences defines model for Experiences.
type Experiences = []Experience

// ObjectId defines model for ObjectId.
type ObjectId struct {
	Id *int64 `json:"id,omitempty"`
}

// Tag defines model for Tag.
type Tag struct {
	Tag string `json:"tag"`
}

// TagArray defines model for TagArray.
type TagArray = []Tag

// TagArrayType defines model for TagArrayType.
type TagArrayType struct {
	Tags *[]Tag `json:"tags,omitempty"`
}

// ListExperiencesParams defines parameters for ListExperiences.
type ListExperiencesParams struct {
	// Limit Size of the page, maximum is 100, default is 25
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page to return
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// CreateExperienceJSONRequestBody defines body for CreateExperience for application/json ContentType.
type CreateExperienceJSONRequestBody = CreateExperienceRequest
